name: Post welcome comment on:
pull equest:
types: [opened]
permissions.
pull-requests: write
jobs:
welcome:
name: Post welcome comment
runs-on buntu-latest
steps:
- run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
enve
GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }} PR_URL: SIl github.event.pul1_request.htm1_url 3Al
